version: "2"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:3000"
            - "443:443"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: always
